-- Backup of employees table created on 2026-09-26T07:19:57.454Z
CREATE TABLE `employees` (
  `id` int NOT NULL AUTO_INCREMENT,
  `candidate_id` int DEFAULT NULL,
  `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `phone` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `join_date` date DEFAULT NULL,
  `status` enum('Active','Inactive','Terminated') COLLATE utf8mb4_general_ci DEFAULT 'Active',
  `sales_target` decimal(12,2) DEFAULT '0.00',
  `branch_id` int DEFAULT NULL,
  `department_id` int DEFAULT NULL,
  `designation_id` int DEFAULT NULL,
  `role_id` int DEFAULT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `gender` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `employment_type` varchar(50) COLLATE utf8mb4_general_ci DEFAULT 'Full-time',
  `salary` decimal(12,2) DEFAULT '0.00',
  `bank_details` text COLLATE utf8mb4_general_ci,
  `emergency_contact` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `address` text COLLATE utf8mb4_general_ci,
  `manager_id` int DEFAULT NULL,
  `team_id` int DEFAULT NULL,
  `profile_photo` longtext COLLATE utf8mb4_general_ci,
  `email_verified` tinyint DEFAULT '0',
  `verification_token` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `account_status` varchar(50) COLLATE utf8mb4_general_ci DEFAULT 'Unregistered',
  `employee_id` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `experience` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `shift_type` varchar(100) COLLATE utf8mb4_general_ci DEFAULT 'Regular Shift',
  `experience_type` varchar(50) COLLATE utf8mb4_general_ci DEFAULT 'Experienced',
  `total_experience_years` int DEFAULT '0',
  `total_experience_months` int DEFAULT '0',
  `relevant_experience_years` int DEFAULT '0',
  `relevant_experience_months` int DEFAULT '0',
  `employee_code` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `blood_group` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `marital_status` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `idx_employees_employee_code_unique` (`employee_code`),
  KEY `branch_id` (`branch_id`),
  KEY `department_id` (`department_id`),
  KEY `designation_id` (`designation_id`),
  KEY `role_id` (`role_id`),
  KEY `fk_employee_manager` (`manager_id`),
  KEY `fk_employee_team` (`team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
