/**
 * Centralized Permission Keys Registry for HRMS
 * Ensures 100% key consistency across Sidebar, PermissionGuard, Page Components, and Backend Routes.
 */
export const PERMISSION_KEYS = {
  DASHBOARD: { module: 'dashboard', submodule: 'dashboard_overview' },
  ORGANIZATION: {
    COMPANY_PROFILE: { module: 'organization', submodule: 'company_profile' },
    DEPARTMENTS: { module: 'organization', submodule: 'departments' },
    DESIGNATIONS: { module: 'organization', submodule: 'designations' },
    TEAMS: { module: 'organization', submodule: 'teams' },
    SHIFT_MANAGEMENT: { module: 'organization', submodule: 'shift_management' },
    HOLIDAY_CALENDAR: { module: 'organization', submodule: 'holiday_calendar' },
    ORGANIZATION_CHART: { module: 'organization', submodule: 'organization_chart' },
  },
  EMPLOYEES: {
    DIRECTORY: { module: 'employees', submodule: 'employee_directory' },
    LIST: { module: 'employees', submodule: 'employee_list' },
    ADD: { module: 'employees', submodule: 'add_employee' },
    PROFILE: { module: 'employees', submodule: 'employee_profile' },
    HISTORY: { module: 'employees', submodule: 'employment_history' },
    PROMOTIONS: { module: 'employees', submodule: 'promotions' },
    TRANSFERS: { module: 'employees', submodule: 'transfers' },
    EXIT: { module: 'employees', submodule: 'exit_management' },
    DOCUMENTS: { module: 'employees', submodule: 'employee_documents' },
  },
  ATTENDANCE: {
    DAILY: { module: 'attendance', submodule: 'daily_attendance' },
    GPS: { module: 'attendance', submodule: 'gps_attendance' },
    GPS_PUNCH: { module: 'attendance', submodule: 'gps_attendance' },
    REGULARIZATION: { module: 'attendance', submodule: 'regularization' },
    SHIFT_ROSTER: { module: 'attendance', submodule: 'shift_roster' },
    OVERTIME: { module: 'attendance', submodule: 'overtime' },
    LATE_ARRIVAL: { module: 'attendance', submodule: 'late_arrival' },
    PUNCH_LOCATIONS: { module: 'attendance', submodule: 'punch_locations' },
  },
  LEAVE: {
    DASHBOARD: { module: 'leave', submodule: 'leave_dashboard' },
    BALANCE: { module: 'leave', submodule: 'leave_balance' },
    MY_LEAVE: { module: 'leave', submodule: 'my_leave' },
    APPROVAL: { module: 'leave', submodule: 'leave_approval' },
    TYPES: { module: 'leave', submodule: 'leave_types' },
    HOLIDAYS: { module: 'leave', submodule: 'holiday_list' },
    COMP_OFF: { module: 'leave', submodule: 'comp_off' },
  },
  PAYROLL: {
    STRUCTURE: { module: 'payroll', submodule: 'salary_structure' },
    COMPONENTS: { module: 'payroll', submodule: 'salary_components' },
    PROCESSING: { module: 'payroll', submodule: 'payroll_processing' },
    PAYSLIPS: { module: 'payroll', submodule: 'generate_payslips' },
    BONUS: { module: 'payroll', submodule: 'bonus_incentives' },
    REIMBURSEMENTS: { module: 'payroll', submodule: 'reimbursements' },
    LOANS: { module: 'payroll', submodule: 'loans_advances' },
    TAX: { module: 'payroll', submodule: 'tax_management' },
  },
  RECRUITMENT: {
    DASHBOARD: { module: 'recruitment', submodule: 'recruitment_dashboard' },
    JOB_OPENINGS: { module: 'recruitment', submodule: 'job_openings' },
    CANDIDATES: { module: 'recruitment', submodule: 'candidates' },
    INTERVIEWS: { module: 'recruitment', submodule: 'interview_schedule' },
    OFFER_LETTERS: { module: 'recruitment', submodule: 'offer_letters' },
    PIPELINE: { module: 'recruitment', submodule: 'hiring_pipeline' },
  },
  ONBOARDING: {
    NEW_JOINERS: { module: 'onboarding', submodule: 'new_joiners' },
    DOC_VERIFICATION: { module: 'onboarding', submodule: 'document_verification' },
    ASSETS: { module: 'onboarding', submodule: 'asset_allocation' },
    WELCOME_KIT: { module: 'onboarding', submodule: 'welcome_kit' },
    ORIENTATION: { module: 'onboarding', submodule: 'orientation' },
    PROBATION: { module: 'onboarding', submodule: 'probation' },
  },
  PERFORMANCE: {
    GOALS: { module: 'performance', submodule: 'goals' },
    KPIS: { module: 'performance', submodule: 'kpis' },
    KRAS: { module: 'performance', submodule: 'kras' },
    APPRAISALS: { module: 'performance', submodule: 'appraisals' },
    REVIEWS: { module: 'performance', submodule: 'reviews' },
    FEEDBACK: { module: 'performance', submodule: 'feedback' },
    PROMOTIONS: { module: 'performance', submodule: 'performance_promotions' },
  },
  PROJECTS: {
    DASHBOARD: { module: 'projects', submodule: 'project_dashboard' },
    LIST: { module: 'projects', submodule: 'projects_list' },
    TASKS: { module: 'projects', submodule: 'tasks' },
    SPRINT_BOARD: { module: 'projects', submodule: 'sprint_board' },
    TIMESHEETS: { module: 'projects', submodule: 'timesheets' },
    MILESTONES: { module: 'projects', submodule: 'milestones' },
    TEAM_MEMBERS: { module: 'projects', submodule: 'team_members' },
  },
  EXPENSES: {
    CLAIMS: { module: 'expenses', submodule: 'expense_claims' },
    CATEGORIES: { module: 'expenses', submodule: 'expense_categories' },
    APPROVAL: { module: 'expenses', submodule: 'expense_approval' },
    REIMBURSEMENTS: { module: 'expenses', submodule: 'expense_reimbursements' },
    REPORTS: { module: 'expenses', submodule: 'expense_reports' },
  },
  DOCUMENTS: {
    EMPLOYEE: { module: 'documents', submodule: 'doc_employee' },
    COMPANY: { module: 'documents', submodule: 'doc_company' },
    POLICIES: { module: 'documents', submodule: 'doc_policies' },
    TEMPLATES: { module: 'documents', submodule: 'doc_templates' },
    SIGNATURES: { module: 'documents', submodule: 'doc_signatures' },
  },
  HELPDESK: {
    DASHBOARD: { module: 'helpdesk', submodule: 'helpdesk_dashboard' },
    TICKETS: { module: 'helpdesk', submodule: 'tickets' },
    CATEGORIES: { module: 'helpdesk', submodule: 'helpdesk_categories' },
    PRIORITIES: { module: 'helpdesk', submodule: 'helpdesk_priorities' },
    KNOWLEDGE_BASE: { module: 'helpdesk', submodule: 'knowledge_base' },
    REPORTS: { module: 'helpdesk', submodule: 'helpdesk_reports' },
  },
  SETTINGS: {
    COMPANY: { module: 'settings', submodule: 'settings_company' },
    BRANDING: { module: 'settings', submodule: 'settings_branding' },
    ORGANIZATION: { module: 'settings', submodule: 'settings_organization' },
    USER_ROLES: { module: 'settings', submodule: 'user_roles' },
    HR: { module: 'settings', submodule: 'settings_hr' },
    COMMUNICATION: { module: 'settings', submodule: 'settings_communication' },
    INTEGRATIONS: { module: 'settings', submodule: 'settings_integrations' },
    SECURITY: { module: 'settings', submodule: 'settings_security' },
    SYSTEM: { module: 'settings', submodule: 'settings_system' },
  },
};
